import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/parts/header'
import Footer from '@/components/parts/footer'
import Button from '@/components/button/button'
import Form from '@/components/form/form'
import Navigation from '@/components/parts/navigation'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <div id="left-sidebar">
        </div>
        <div id="main-content">
          <div id="blog">
            <h1>This is a sample blog text</h1>
            <p>Lorem ipsum dolor sit amet, <a href="">consecteturconsectetur adipiscing elit</a>, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor <strong>incididunt ut</strong> labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              Lorem ipsum dolor sit amet, <a href="">consectetur</a> adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <ul>
              <li>sesame</li>
              <li>beans</li>
              <li>yoghurt</li>
            </ul>
            <ol>
              <li>new york</li>
              <li>los angeles</li>
              <li>san francisco</li>
            </ol>
          </div>
          <hr></hr>
          <pre>
          <code>asds
            asdsasd
          </code>
          </pre>
          <Form
            id={'chatbot'}
            title={'Chatbot'}
            fields={[
                {name: 'Ask a question', type: 'textarea'},
                {name: 'Send', type: 'button'}
              ]}
              onClick={'#'} >
          </Form>
          <Form
            id={'123'}
            title={'Login Form'}
            fields={[
                {name: 'Username',  type: 'text'},
                {name: 'Password',  type: 'password'},
                {name: 'Comments',  type: 'textarea'},
                {name: 'Send',      type: 'button'}
              ]}
              onClick={'#'} >
          </Form>
        </div>
        <div id="right-sidebar">

        </div>
      </main>
      <Footer />
    </>
  )
}
